---
- name: Display OS variable
  debug:
    var: OS

# Configure nos3 permissions, env, etc.
- name:  Add nos3 user to various groups
  become: yes
  user:
    name: nos3
    groups: domainusers, dialout, vagrant, vboxsf, root, docker
  tags: base
  # Note: group root needed to find necessary library files to build

- name: Add nos3 user as a sudoer
  become: yes
  lineinfile:
    path: /etc/sudoers.d/nos3
    create: yes
    line: 'nos3 ALL=(ALL) NOPASSWD:ALL'
  tags: base

# Hide the vagrant user
- name:  Hide vagrant user
  become: yes
  blockinfile:
    path: /var/lib/AccountsService/users/vagrant
    create: yes
    mode: '0666'
    marker: "# {mark} Ansible managed launch hide vagrant user block"
    block: |
      [User]
      SystemAccount=true
  tags: base

# RedHat change vagrant password
- name: Change vagrant password on RedHat
  become: yes
  when: ansible_facts['os_family'] == "RedHat"
  shell:
    cmd: usermod -p vagrant vagrant

# NOTE:  Not sure this is the best way to do this... there are some hardwired things based on experiences with Oracle Linux 8.5 and Install Desktop Environment
# Virtual Box
- name: Guest additions
  tags: guest-additions
  block:
  - name: Install guest additions required packages for Rocky
    become: yes
    when: (OS == "rocky") and ansible_facts['os_family'] == "RedHat"
    package:
      name: 
        - gcc 
        - kernel
        - kernel-devel 
        - kernel-headers 
        - dkms 
        - make 
        - bzip2 
        - perl
      state: latest
  - name: Install guest additions required packages for Oracle
    become: yes
    when: (OS == "oracle") and (ansible_facts['os_family'] == "RedHat")
    package:
      name: 
        - "kernel-uek-devel-5.4.17-2136.315.5.el8uek.x86_64"
  - name: Build guest additions for new Oracle kernel
    become: yes
    when: (OS == "oracle") and (ansible_facts['os_family'] == "RedHat")
    shell:
      cmd: /sbin/rcvboxadd quicksetup 5.4.17-2136.315.5.el8uek.x86_64

  - name: Install guest additions required packages for Ubuntu
    become: yes
    when: ansible_facts['os_family'] == "Debian"
    package:
      name: "linux-headers-{{ ansible_kernel }}"