---
- name: Display OS variable
  debug:
    var: OS

# Configure jstar permissions, env, etc.
- name:  Add jstar user to various groups
  become: yes
  user:
    name: jstar
    groups: domainusers, dialout, vagrant, vboxsf, root, docker
  tags: base
  # Note: group root needed to find necessary library files to build

- name: Add jstar user as a sudoer
  become: yes
  lineinfile:
    path: /etc/sudoers.d/jstar
    create: yes
    line: 'jstar ALL=(ALL) NOPASSWD:ALL'
  tags: base

# Hide the vagrant user
- name:  Hide vagrant user
  become: yes
  blockinfile:
    path: /var/lib/AccountsService/users/vagrant
    create: yes
    mode: '0666'
    marker: "# {mark} Ansible managed launch hide vagrant user block"
    block: |
      [User]
      SystemAccount=true
  tags: base

# RedHat change vagrant password
- name: Change vagrant password on RedHat
  become: yes
  when: ansible_facts['os_family'] == "RedHat"
  shell:
    cmd: usermod -p vagrant vagrant

# NOTE:  Not sure this is the best way to do this... there are some hardwired things based on experiences with Oracle Linux 8.5 and Install Desktop Environment
# Virtual Box
- name: Guest additions
  tags: guest-additions
  block:
  - name: Install guest additions required packages for Rocky
    become: yes
    when: (OS == "rocky") and ansible_facts['os_family'] == "RedHat"
    package:
      name: 
        - gcc 
        - kernel
        - kernel-devel 
        - kernel-headers 
        - dkms 
        - make 
        - bzip2 
        - perl
      state: latest
  - name: Install guest additions required packages for Oracle
    become: yes
    when: (OS == "oracle") and (ansible_facts['os_family'] == "RedHat")
    package:
      name: 
        - "kernel-uek-devel-5.4.17-2136.315.5.el8uek.x86_64"
  - name: Build guest additions for new Oracle kernel
    become: yes
    when: (OS == "oracle") and (ansible_facts['os_family'] == "RedHat")
    shell:
      cmd: /sbin/rcvboxadd quicksetup 5.4.17-2136.315.5.el8uek.x86_64

  - name: Install guest additions required packages for Ubuntu
    become: yes
    when: ansible_facts['os_family'] == "Debian"
    package:
      name: "linux-headers-{{ ansible_kernel }}"

# Bring back nice to haves in Gnome
- name: GNOME Nice to haves
  tags: gnome-nice-to-haves
  block:
  - name: Download get-pip.py for Rocky
    when: (OS == "rocky")
    ansible.builtin.get_url:
      url: https://bootstrap.pypa.io/pip/3.6/get-pip.py # Hardcoded 3.6
      dest: /tmp/get-pip.py
      mode: '0440'
  - name: Download get-pip.py for Oracle or Ubuntu
    when: (OS == "oracle") or (OS == "ubuntu")
    ansible.builtin.get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /tmp/get-pip.py
      mode: '0440'
  - name: Execute pip install script for the ansible python version
    become: true
    script: /tmp/get-pip.py
    args:
      executable: "{{ ansible_python.executable }}"
  - name: PIP install psutil
    become: true
    command: "{{ ansible_python.executable }} -m pip install psutil"
  - name: GNOME Preferences (Minimize, maximize, close buttons)
    become: true
    become_user: jstar
    community.general.dconf:
      key: "/org/gnome/desktop/wm/preferences/button-layout"
      value: "':minimize,maximize,close'"
      state: present    
  - name: GNOME Preferences (Window list)
    become: true
    become_user: jstar
    dconf:
      key: "/org/gnome/shell/enabled-extensions"
      value: "['window-list@gnome-shell-extensions.gcampax.github.com']"
      state: present
  - name: Disable idle delay
    dconf:
      key: "/org/gnome/desktop/session/idle-delay"
      value: 'uint32 0'
      state: present
  - name: Disable idle activation
    dconf:
      key: "/org/gnome/desktop/screensaver/idle-activation-enabled"
      value: "'false'"
      state: present
  - name: Disable lock
    dconf:
      key: "/org/gnome/desktop/screensaver/lock-enabled"
      value: "'false'"
      state: present
  - name: Favorites
    dconf:
      key: "/org/gnome/shell/favorite-apps"
      value: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop']"
      state: present
  - name: Ignore new release
    dconf:
      key: "/com/ubuntu/update-manager/check-new-release-ignore"
      value: "'jammy'"
      state: present

# Conky
- name: Install conky for RHEL
  become: yes
  when: ansible_facts['os_family'] == "RedHat"
  package:
    name: 
      - conky
    state: latest
- name: Install conky for Ubuntu
  become: yes
  when: ansible_facts['os_family'] == "Debian"
  package:
    name: 
      - conky-all
    state: latest
- name: configure conky
  become: yes
  block:
    - name: Create conky autostart directory
      file:
        path: /home/jstar/.config/autostart
        state: directory
    - name: Create conky config directory
      file:
        path: /home/jstar/.config/conky
        state: directory
    - name: Copy conky config
      copy:
        src: files/conky.conf
        dest: /home/jstar/.config/conky
    - name: Configure conky autostart
      copy:
        src: files/conky.desktop
        dest: /home/jstar/.config/autostart/
