---
# nos3-user role
# user account, env vars, etc.

# Create nos3 user and group
- name: Create domainusers group
  become: yes
  group:
    name: domainusers
  tags: base

- name: Create docker group
  become: yes
  group:
    name: docker
  tags: base

- name:  Create nos3 user and add nos3 groups
  become: yes
  user:
    name: nos3
    password: $6$.mG1a/zL$f1LcckhnvYRUxQZrGeWVBh.nNAJu9qNIX9v1zvivsc67SjqGapbXNFS4e2/uInkqSas64WwmBRJ45uqSB.nSZ1
    group: domainusers
    groups: domainusers, dialout, docker
    shell: /bin/bash
  tags: base

# Change /opt/nos3 directory ownership
- name: Change /opt/nos3 directory ownership
  become: yes
  file:
    path: /opt/nos3
    state: directory
    owner: nos3
    group: domainusers
  tags: base

# Edit permissions for /opt/nos3
- name: Change /opt/nos3 directory permissions
  become: yes
  file:
    path: /opt/nos3
    mode: '777'
  tags: base

# Configure nos3 permissions, env, etc.
- name: Set nos3 as owner of home directory
  become: yes
  ansible.builtin.file:
    path: /home/nos3
    state: directory
    recurse: yes
    owner: nos3
    group: domainusers
  tags: base
- name: Copy ssh keys to nos3
  become: yes
  block:
  - name: Touch .ssh
    file:
      path: /home/nos3/.ssh
      state: directory
      mode: '0700'
      owner: nos3
      group: domainusers
  - name: Create .ssh agent env file if it does not exist
    copy:
      content: ''
      dest: /home/nos3/.ssh/agent.env
      force: no
      mode: '0600'
      owner: nos3
      group: domainusers
- name:  Auto load ssh key
  become: yes
  blockinfile:
    path: /home/nos3/.bashrc
    create: yes
    owner: nos3
    group: domainusers
    marker: "# {mark} Ansible managed auto load ssh key block"
    block: |
        # Automatically load ssh key when a terminal is opened
        env=~/.ssh/agent.env
        agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }
        agent_start () {
            (umask 077; ssh-agent >| "$env")
            . "$env" >| /dev/null ; }
        agent_load_env
        # agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
        agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)
        if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
            agent_start
            ssh-add
        elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
            ssh-add
        fi
        unset env
  tags: base
- name: Configure gdb
  become: yes
  lineinfile:
    path: /home/nos3/.gdbinit
    create: yes
    mode: '0666'
    owner: nos3
    group: domainusers
    line: 'handle all ignore nostop noprint'
  tags: base
- name:  Set up nos3 user environment # min:106, custom:25
  debug:
    msg: TODO - Set up nos3 user environment (Desktop, convenience scripts)
  tags: base
